version: "5.9"
services:
  web:
    container_name: web
    build:
      context: ..
      dockerfile: ./Productivity.API/Dockerfile
    depends_on:
      - mssql
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - base
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    environment:
      SA_PASSWORD: "Pass123!"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    ports:
      - "11433:1433"
    networks:
      - base
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    networks:
      - base
networks:
   base:
